# Generated by Django 5.2.1 on 2025-06-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='alt_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
