# Generated by Django 5.2.1 on 2025-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        )
    ]
