# Generated by Django 5.2.1 on 2025-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_variant_orderitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(default=1, upload_to='ordered_product_variants/'),
            preserve_default=False,
        ),
    ]
